# Generated by Django 5.0.7 on 2024-10-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
