# Generated by Django 5.0.7 on 2024-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brandmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
