# Generated by Django 5.0.7 on 2024-10-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='image',
            field=models.ImageField(upload_to='cars/uploads'),
        ),
    ]
