# Generated by Django 5.0.7 on 2024-10-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carsmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='quanity',
            field=models.IntegerField(default=0),
        ),
    ]
