# Generated by Django 5.0.7 on 2024-10-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carsmodel_quanity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsmodel',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
