# Generated by Django 5.0.7 on 2024-10-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_commentmodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
