# Generated by Django 5.0.7 on 2024-10-09 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_commentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cars.carsmodel'),
        ),
    ]
